export enum JobOpeningStatus {
    DRAFT = 'DRAFT',
    OPEN = 'OPEN',
    ON_HOLD = 'ON_HOLD',
    FILLED = 'FILLED',
    CANCELLED = 'CANCELLED',
    CLOSED = 'CLOSED',
  }
  
  export enum JobType {
    FULL_TIME = 'FULL_TIME',
    PART_TIME = 'PART_TIME',
    PERMANENT = 'PERMANENT',
    CONTRACT = 'CONTRACT',
    INTERNSHIP = 'INTERNSHIP',
    ANY = 'ANY',
  }
  
  export enum WorkExperience {
    NONE = 'None',
    FRESHER = 'Fresher',
    '0_1_YEAR' = '0-1 Year',
    '1_3_YEARS' = '1-2 Years',
    '4_5_YEARS' = '2-3 Years',
    '5PLUS_YEARS' = '5+ Years',
  }
  
  export enum JobLocation {
    REMOTE = 'Remote',
    ONSITE = 'Onsite',
    HYBRID = 'Hybrid',
  }
  
  export enum ApplicationQuestionType {
    DEFAULT = 'DEFAULT',
    ADDITIONAL = 'ADDITIONAL',
  }
  
  export enum ApplicationDefaultQuestionType {
    RESUME = 'RESUME',
    COVER_LETTER = 'COVER_LETTER',
    HIGHER_EDUCATION = 'HIGHER_EDUCATION',
    DESIRED_SALARY = 'DESIRED_SALARY',
    ADDRESS = 'ADDRESS',
    LINKEDIN_URL = 'LINKEDIN_URL ',
    COLLEGE_UNIVERSITY = 'COLLEGE_UNIVERSITY',
    CURRENT_COMPANY_NAME = 'CURRENT_COMPANY_NAME',
    REFFERED_BY = 'REFFERED_BY',
    WEBSITE_PORTFOLIO = 'WEBSITE_PORTFOLIO',
  }
  
  export enum AppplicationAdditionalQuestionType {
    SHORT_ANSWER = 'SHORT_ANSWER',
    LONG_ANSWER = 'LONG_ANSWER',
    YES_NO = 'YES_NO',
    MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
    FILE_UPLOAD = 'FILE_UPLOAD',
  }
  
  export enum Industries {
    NONE = 'None',
    ADMINISTRATION = 'Administration',
    ADVERTISING = 'Advertising',
    AGRICULTURE = 'Agriculture',
    ARCHITECTURE_CONSTRUCTION = 'Architecture & Construction',
    ARTS_GRAPHICS = 'Arts & Graphics',
    AIRLINE_AVIATION = 'Airline - Aviation',
    ACCOUNTING = 'Accounting',
    AUTOMOTIVE = 'Automotive',
    BANKING = 'Banking',
    BIOTECHNOLOGY = 'Biotechnology',
    BROADCASTING = 'Broadcasting',
    BUSINESS_MANAGEMENT = 'Business Management',
    CHARITY = 'Charity',
    CATERING = 'Catering',
    CUSTOMER_SERVICE = 'Customer Service',
    CHEMICALS = 'Chemicals',
    CONSTRUCTION = 'Construction',
    COMMUNICATIONS = 'Communications',
    CONSULTING = 'Consulting',
    COMPUTER = 'Computer',
    CONSUMER = 'Consumer',
    COSMETICS = 'Cosmetics',
    DESIGN = 'Design',
    DEFENCE = 'Defence',
    EDUCATION = 'Education',
    ELECTRONICS = 'Electronics',
    ENGINEERING = 'Engineering',
    ENERGY_UTILITIES = 'Energy and Utilities',
    ENTERTAINMENT = 'Entertainment',
    EMPLOYMENT_RECRUITING_STAFFING = 'Employment - Recruiting - Staffing',
    ENVIRONMENTAL = 'Environmental',
    EXERCISE_FITNESS = 'Exercise - Fitness',
    EXPORT_IMPORT = 'Export/Import',
    FINANCIAL_SERVICES = 'Financial Services',
    FASHION = 'Fashion',
    FMCG_FOODS_BEVERAGE = 'FMCG/Foods/Beverage',
    FERTILIZERS_PESTICIDES = 'Fertilizers/Pesticides',
    FURNITURE = 'Furniture',
    GROCERY = 'Grocery',
    GAS = 'Gas',
    GOVERNMENT = 'Government',
    GOVERNMENT_MILITARY = 'Government/Military',
    GOVERNMENT_PUBLIC_SECTOR = 'Government & Public Sector',
    GEMS_JEWELLERY = 'Gems & Jewellery',
    HEALTH_CARE = 'Health Care',
    HUMAN_RESOURCES = 'Human Resources',
    HOSPITALITY = 'Hospitality',
    HOTELS_LODGING = 'Hotels and Lodging',
    HVAC = 'HVAC',
    HARDWARE = 'Hardware',
    INSURANCE = 'Insurance',
    INSTALLATION = 'Installation',
    IT_SERVICES = 'IT Services',
    INDUSTRIAL = 'Industrial',
    INTERNET_SERVICES = 'Internet Services',
    IMPORT_EXPORT = 'Import - Export',
    LEGAL = 'Legal',
    LOGISTICS = 'Logistics',
    LANDSCAPING = 'Landscaping',
    LEISURE_SPORT = 'Leisure and Sport',
    LIBRARY_SCIENCE = 'Library Science',
    MARKETING = 'Marketing',
    MANUFACTURING = 'Manufacturing',
    MANAGEMENT = 'Management',
    MERCHANDISING = 'Merchandising',
    MEDICAL = 'Medical',
    MEDIA = 'Media',
    METALS = 'Metals',
    MINING = 'Mining',
    MILITARY = 'Military',
    MORTGAGE = 'Mortgage',
    MARINE = 'Marine',
    MARITIME = 'Maritime',
    NONPROFIT_CHARITABLE_ORGANIZATIONS = 'Nonprofit Charitable Organizations',
    NGO_SOCIAL_SERVICES = 'NGO/Social Services',
    NEWSPAPER = 'Newspaper',
    OIL_GAS = 'Oil & Gas',
    OTHER = 'Other',
    OTHER_NOT_CLASSIFIED = 'Other/Not Classified',
    PHARMA = 'Pharma',
    POLYMER_PLASTIC_RUBBER = 'Polymer / Plastic / Rubber',
    PHARMA_BIOTECH_CLINICAL_RESEARCH = 'Pharma/Biotech/Clinical Research',
    PUBLIC_SECTOR_GOVERNMENT = 'Public Sector and Government',
    PRINTING_PACKAGING_PUBLISHING = 'Printing/Packaging/Publishing',
    PERSONAL_HOUSEHOLD_SERVICES = 'Personal and Household Services',
    PROPERTY_REAL_ESTATE = 'Property & Real Estate',
    PAPER = 'Paper',
    PET_STORE = 'Pet Store',
    PUBLIC_RELATIONS = 'Public Relations',
    REAL_ESTATE = 'Real Estate',
    RETAIL = 'Retail',
    RETAIL_WHOLESALE = 'Retail & Wholesale',
    RECREATION = 'Recreation',
    REAL_ESTATE_PROPERTY = 'Real Estate and Property',
    RECRUITMENT_EMPLOYMENT_FIRM = 'Recruitment/Employment Firm',
    REAL_ESTATE_PROPERTY_MANAGEMENT = 'Real Estate/Property Management',
    RESTAURANT_FOOD_SERVICES = 'Restaurant/Food Services',
    RENTAL_SERVICES = 'Rental Services',
    RESEARCH_DEVELOPMENT = 'Research & Development',
    REPAIR_MAINTENANCE_SERVICES = 'Repair / Maintenance Services',
    SERVICES = 'Services',
    SALES_MARKETING = 'Sales - Marketing',
    SCIENCE_TECHNOLOGY = 'Science & Technology',
    SECURITY_LAW_ENFORCEMENT = 'Security/Law Enforcement',
    SHIPPING_MARINE = 'Shipping/Marine',
    SECURITY_SURVEILLANCE = 'Security and Surveillance',
    SPORTS_PHYSICAL_RECREATION = 'Sports and Physical Recreation',
    STAFFING_EMPLOYMENT_AGENCIES = 'Staffing/Employment Agencies',
    SOCIAL_SERVICES = 'Social Services',
    SPORTS_LEISURE_LIFESTYLE = 'Sports Leisure & Lifestyle',
    SEMICONDUCTOR = 'Semiconductor',
    TECHNOLOGY = 'Technology',
    SERVICES_CORPORATE_B2B = 'Services - Corporate B2B',
    TRAVEL = 'Travel',
    TRAINING = 'Training',
    TRANSPORTATION = 'Transportation',
    TELECOMMUNICATIONS = 'Telecommunications',
    TRADE_SERVICES = 'Trade and Services',
    TRAVEL_TOURISM = 'Travel and Tourism',
    TEXTILES_GARMENTS_ACCESSORIES = 'Textiles/Garments/Accessories',
    TYRES = 'Tyres',
    UTILITIES = 'Utilities',
    WIRELESS = 'Wireless',
    WOOD_FIBRE_PAPER = 'Wood / Fibre / Paper',
    WASTE_MANAGEMENT = 'Waste Management',
    WHOLESALE_TRADE_IMPORT_EXPORT = 'Wholesale Trade/Import-Export',
  }
  
  export enum JobPipelineStageType {
    NEW = 'NEW',
    RESUME_SHORTLIST = 'RESUME_SHORTLIST',
    PHONE_SCREEN = 'PHONE_SCREEN',
    INTERVIEW = 'INTERVIEW',
    APTITUDE_ONLIE_ASSESSMENT = 'APTITUDE_ONLIE_ASSESSMENT',
    TECHNICAL_INTERVIEW_R_1 = 'TECHNICAL_INTERVIEW_R_1',
    TECHNICAL_INTERVIEW_R_2 = 'TECHNICAL_INTERVIEW_R_2',
    MANAGERIAL_INTERVIEW = 'MANAGERIAL_INTERVIEW',
    HR_INTERVIEW = 'HR_INTERVIEW',
    OFFER = 'OFFER',
    HIRED = 'HIRED',
  }
  